// Generated by: npx supabase gen types typescript --project-id <id>
// Placeholder until Task 9 when the schema is created and types are regenerated.
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
